### ISSUE TITLE
Node v0.12.7: Method Map.prototype.size called on incompatible receiver

### ISSUE THREAD

**Issue by davisjam** [xk/JASON#10]
JASON doesn't work on node version 0.12.7.

```
(11:06:16) jamie@suwarna7-Lenovo-K450e ~ $ node -v
v0.12.7
(11:06:17) jamie@suwarna7-Lenovo-K450e ~ $ npm install JASON
/home/jamie3
└── JASON@0.1.3 

npm WARN enoent ENOENT, open '/home/jamie3/package.json'
npm WARN jamie3 No description
npm WARN jamie3 No repository field.
npm WARN jamie3 No README data
npm WARN jamie3 No license field.
(11:06:22) jamie@suwarna7-Lenovo-K450e ~ $ node
> var JASON = require('JASON')
TypeError: Method Map.prototype.size called on incompatible receiver #<Map>
    at Map.size (native)
    at /home/jamie3/node_modules/JASON/index.js:268:37
    at Array.forEach (native)
    at strfy (/home/jamie3/node_modules/JASON/index.js:267:10)
    at /home/jamie3/node_modules/JASON/index.js:53:5
    at Object.<anonymous> (/home/jamie3/node_modules/JASON/index.js:287:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by davisjam** [comment]
This issue still shows up on #9 by @slang800. @slang800 thoughts?

**Comment by jonatino** [comment]
@davisjam Have you fixed this issue?

**Comment by davisjam** [comment]
No. Though I don't think node v0.X is a good idea at this point.
